package com.groupeO.gestiondestock.exception;

public enum ErrorCodes {
    ARTICLE_NOT_FOUND("ARTICLE_NOT_FOUND"),
    ARTICLE_NOT_VALID("ARTICLE_NOT_VALID"),

    CATEGORIE_NOT_FOUND("CATEGORIE_NOT_FOUND"),
    CATEGORIE_NOT_VALID("CATEGORIE_NOT_VALID"),

    //TODO complete the rest of the error codes
    ENTREPRISE_NOT_FOUND("ENTREPRISE_NOT_FOUND"),
    ENTREPRISE_NOT_VALID("ENTREPRISE_NOT_VALID"),

    CLIENT_NOT_FOUND("CLIENT_NOT_FOUND"),
    CLIENT_NOT_VALID("CLIENT_NOT_VALID"),

    FOURNISSEUR_NOT_FOUND("FOURNISSEUR_NOT_FOUND"),
    FOURNISSEUR_NOT_VALID("FOURNISSEUR_NOT_VALID"),

    LIGNE_COMMANDE_CLIENT_NOT_FOUND("LIGNE_COMMANDE_CLIENT_NOT_FOUND"),
    LIGNE_COMMANDE_CLIENT_NOT_VALID("LIGNE_COMMANDE_CLIENT_NOT_VALID"),

    LIGNE_COMMANDE_FOURNISSEUR_NOT_FOUND("LIGNE_COMMANDE_FOURNISSEUR_NOT_FOUND"),
    LIGNE_COMMANDE_FOURNISSEUR_NOT_VALID("LIGNE_COMMANDE_FOURNISSEUR_NOT_VALID"),

    LIGNE_VENTE_NOT_FOUND("LIGNE_VENTE_NOT_FOUND"),
    LIGNE_VENTE_NOT_VALID("LIGNE_VENTE_NOT_VALID"),

    MVT_STK_NOT_FOUND("MVT_STK_NOT_FOUND"),
    MVT_STK_NOT_VALID("MVT_STK_NOT_VALID"),

    UTILISATEUR_NOT_FOUND("UTILISATEUR_NOT_FOUND"),
    UTILISATEUR_NOT_VALID("UTILISATEUR_NOT_VALID"),

    COMMANDE_CLIENT_NOT_FOUND("COMMANDE_CLIENT_NOT_FOUND"),
    COMMANDE_CLIENT_NOT_VALID("COMMANDE_CLIENT_NOT_VALID"),

    ROLES_NOT_FOUND("ROLES_NOT_FOUND"),
    ROLES_NOT_VALID("ROLES_NOT_VALID"),

    COMMANDE_FOURNISSEUR_NOT_FOUND("COMMANDE_FOURNISSEUR_NOT_FOUND"),
    COMMANDE_FOURNISSEUR_NOT_VALID("COMMANDE_FOURNISSEUR_NOT_VALID"),

    CATEGORY_NOT_FOUND("CATEGORY_NOT_FOUND"),
    CATEGORY_NOT_VALID("CATEGORY_NOT_VALID"),

    UNSUPPORTED_MEDIA_TYPE("UNSUPPORTED_MEDIA_TYPE"),


    VENTES_NOT_FOUND("VENTES_NOT_FOUND"),
    VENTES_NOT_VALID("VENTES_NOT_VALID"),
    IMAGE_FORMAT_NOT_SUPPORTED("IMAGE_FORMAT_NOT_SUPPORTED"),
    
    INVALID_CREDENTIALS("INVALID_CREDENTIALS");


    private final String code;

    private ErrorCodes(String code) {    
        this.code = code;
    }

    public String getCode() {
        return code;
    }

}
